package com.adingrt.vacuumworld.ui;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Adin Rubio
 */
public class VacuumWorldUI extends javax.swing.JFrame {
    /**
     * Creates new form mainPrueba
     */
    public VacuumWorldUI() {
        initComponents();

        this.lbl00.setIcon(this.setIcono("/img/aspiradora.jpg", this.lbl00));
        this.lbl01.setIcon(this.setIcono("/img/suciedad.jpg", this.lbl01));
        this.lbl11.setIcon(this.setIcono("/img/suciedad.jpg", this.lbl11));
        //this.panelPrincipal.add(aspiradora);
        //this.panelPrincipal.add(suciedad);
        //this.panelPrincipal.updateUI();
        
        //this.aspiradora.getjLabel1().setIcon(this.setIcono("/img/aspiradora.jpg", this.aspiradora.getjLabel1()));
        //this.suciedad.getjLabel1().setIcon(this.setIcono("/img/suciedad.jpg", this.suciedad.getjLabel1()));
        
        
        
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelPrincipal = new javax.swing.JPanel();
        panelEstadoInicial = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        panelMovimiento = new javax.swing.JPanel();
        lbl00 = new javax.swing.JLabel();
        lbl10 = new javax.swing.JLabel();
        lbl01 = new javax.swing.JLabel();
        lbl11 = new javax.swing.JLabel();
        panelHeuristica = new javax.swing.JPanel();
        panelResultado = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        panelPrincipal.setLayout(new java.awt.GridBagLayout());

        panelEstadoInicial.setBackground(new java.awt.Color(51, 255, 0));
        panelEstadoInicial.setMaximumSize(new java.awt.Dimension(0, 0));
        panelEstadoInicial.setMinimumSize(new java.awt.Dimension(0, 0));
        panelEstadoInicial.setPreferredSize(new java.awt.Dimension(480, 300));
        panelEstadoInicial.setLayout(new java.awt.GridLayout(1, 2));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 0)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 231, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 186, Short.MAX_VALUE)
        );

        panelEstadoInicial.add(jPanel3);

        panelMovimiento.setBackground(new java.awt.Color(255, 255, 255));
        panelMovimiento.setLayout(new java.awt.GridLayout(2, 2));

        lbl00.setForeground(new java.awt.Color(0, 0, 0));
        lbl00.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl00.setText("ASPIRADORA 0,0");
        lbl00.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        lbl00.setMaximumSize(new java.awt.Dimension(0, 0));
        lbl00.setMinimumSize(new java.awt.Dimension(0, 0));
        lbl00.setPreferredSize(new java.awt.Dimension(50, 50));
        panelMovimiento.add(lbl00);

        lbl10.setForeground(new java.awt.Color(0, 0, 0));
        lbl10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl10.setText("ASPIRADORA 1,0");
        lbl10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        lbl10.setMaximumSize(new java.awt.Dimension(0, 0));
        lbl10.setMinimumSize(new java.awt.Dimension(0, 0));
        lbl10.setPreferredSize(new java.awt.Dimension(50, 50));
        panelMovimiento.add(lbl10);

        lbl01.setForeground(new java.awt.Color(0, 0, 0));
        lbl01.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl01.setText("SUCIEDAD 0,1");
        lbl01.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        lbl01.setMaximumSize(new java.awt.Dimension(0, 0));
        lbl01.setMinimumSize(new java.awt.Dimension(0, 0));
        lbl01.setPreferredSize(new java.awt.Dimension(50, 50));
        panelMovimiento.add(lbl01);

        lbl11.setForeground(new java.awt.Color(0, 0, 0));
        lbl11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl11.setText("SUCIEDAD 1,1");
        lbl11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        lbl11.setMaximumSize(new java.awt.Dimension(0, 0));
        lbl11.setMinimumSize(new java.awt.Dimension(0, 0));
        lbl11.setPreferredSize(new java.awt.Dimension(50, 50));
        panelMovimiento.add(lbl11);

        panelEstadoInicial.add(panelMovimiento);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.6;
        panelPrincipal.add(panelEstadoInicial, gridBagConstraints);

        panelHeuristica.setBackground(new java.awt.Color(51, 51, 51));
        panelHeuristica.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 0)));
        panelHeuristica.setMaximumSize(new java.awt.Dimension(0, 0));
        panelHeuristica.setPreferredSize(new java.awt.Dimension(480, 300));

        javax.swing.GroupLayout panelHeuristicaLayout = new javax.swing.GroupLayout(panelHeuristica);
        panelHeuristica.setLayout(panelHeuristicaLayout);
        panelHeuristicaLayout.setHorizontalGroup(
            panelHeuristicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelHeuristicaLayout.setVerticalGroup(
            panelHeuristicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.2;
        panelPrincipal.add(panelHeuristica, gridBagConstraints);

        panelResultado.setBackground(new java.awt.Color(51, 51, 51));
        panelResultado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 0)));
        panelResultado.setMaximumSize(new java.awt.Dimension(0, 0));
        panelResultado.setPreferredSize(new java.awt.Dimension(480, 300));

        javax.swing.GroupLayout panelResultadoLayout = new javax.swing.GroupLayout(panelResultado);
        panelResultado.setLayout(panelResultadoLayout);
        panelResultadoLayout.setHorizontalGroup(
            panelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelResultadoLayout.setVerticalGroup(
            panelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.2;
        panelPrincipal.add(panelResultado, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VacuumWorldUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VacuumWorldUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VacuumWorldUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VacuumWorldUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VacuumWorldUI().setVisible(true);
            }
        });
    }

    public Icon setIcono(String ruta, JLabel label) {
        ImageIcon icon = new ImageIcon(getClass().getResource(ruta));
        //int ancho = 10;
        int ancho = label.getWidth();
        //int alto = 10;
        int alto = label.getHeight();
        ImageIcon icono = new ImageIcon(icon.getImage().getScaledInstance(ancho, alto, Image.SCALE_AREA_AVERAGING));
        return icono;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbl00;
    private javax.swing.JLabel lbl01;
    private javax.swing.JLabel lbl10;
    private javax.swing.JLabel lbl11;
    private javax.swing.JPanel panelEstadoInicial;
    private javax.swing.JPanel panelHeuristica;
    private javax.swing.JPanel panelMovimiento;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelResultado;
    // End of variables declaration//GEN-END:variables
}
